### ISSUE TITLE
Issue with https://fedify.dev/

### ISSUE THREAD

**Issue by mattcam** [dahlia/fedify#57] opened 2024-06-09 09:39 UTC
When browsing to website https://fedify.dev/ chrome reports that the connection is not secure.

**Comment by dahlia** [comment] 2024-06-09 10:58
I can't reproduce this on my machine.  What OS are you using and what is your Chrome version?  Can you take a screenshot of Chrome and show me?

**Comment by mattcam** [comment] 2024-06-09 12:40
Mac with chrome Version 125.0.6422.142 (Official Build) (arm64)

Screen grab follows
![Screenshot 2024-06-09 at 10 39 51 pm](https://github.com/dahlia/fedify/assets/3451548/f1cccd69-4f03-4b88-8070-e41043f08cfa)

**Comment by dahlia** [comment] 2024-06-09 14:20
What does a TLS certificate look like? It should look something like below:

![](https://github.com/dahlia/fedify/assets/12431/9b5e31bd-2c90-44f3-b103-530cd85e47f6)
![](https://github.com/dahlia/fedify/assets/12431/3f4976fb-6348-446d-b0f6-2e1f7e23fdea)

**Comment by mattcam** [comment] 2024-06-09 23:00
Maybe it is something at my end. On desktop don't see the certificate, just see issue on various broswers. Got it to work on mobile device using safari and chrome with wifi turned off (e.g. using mobile data).

**Comment by dahlia** [comment] 2024-06-10 01:38
Okay, let's close this issue then.

**Closed by dahlia** 2024-06-10 01:38 UTC
